

package dev.zacsweers.redacted.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.zacsweers.redacted.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-tests/src/test/data/diagnostic")
@TestDataPath("$PROJECT_ROOT")
public class DiagnosticTestGenerated extends AbstractDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostic() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-tests/src/test/data/diagnostic"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("AnnotatedValueProp.kt")
  public void testAnnotatedValueProp() {
    runTest("compiler-tests/src/test/data/diagnostic/AnnotatedValueProp.kt");
  }

  @Test
  @TestMetadata("CustomToString.kt")
  public void testCustomToString() {
    runTest("compiler-tests/src/test/data/diagnostic/CustomToString.kt");
  }

  @Test
  @TestMetadata("DataObject.kt")
  public void testDataObject() {
    runTest("compiler-tests/src/test/data/diagnostic/DataObject.kt");
  }

  @Test
  @TestMetadata("DoubleAnnotation.kt")
  public void testDoubleAnnotation() {
    runTest("compiler-tests/src/test/data/diagnostic/DoubleAnnotation.kt");
  }

  @Test
  @TestMetadata("EnumClass.kt")
  public void testEnumClass() {
    runTest("compiler-tests/src/test/data/diagnostic/EnumClass.kt");
  }

  @Test
  @TestMetadata("NonDataClass.kt")
  public void testNonDataClass() {
    runTest("compiler-tests/src/test/data/diagnostic/NonDataClass.kt");
  }
}
