

package dev.zacsweers.redacted.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.zacsweers.redacted.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("redacted-compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("redacted-compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("ClassAnnotated.kt")
  public void testClassAnnotated() {
    runTest("redacted-compiler-plugin/testData/box/ClassAnnotated.kt");
  }

  @Test
  @TestMetadata("Complex.kt")
  public void testComplex() {
    runTest("redacted-compiler-plugin/testData/box/Complex.kt");
  }

  @Test
  @TestMetadata("CustomAnnotationReplacement.kt")
  public void testCustomAnnotationReplacement() {
    runTest("redacted-compiler-plugin/testData/box/CustomAnnotationReplacement.kt");
  }

  @Test
  @TestMetadata("CustomReplacement.kt")
  public void testCustomReplacement() {
    runTest("redacted-compiler-plugin/testData/box/CustomReplacement.kt");
  }

  @Test
  @TestMetadata("ValueClass.kt")
  public void testValueClass() {
    runTest("redacted-compiler-plugin/testData/box/ValueClass.kt");
  }
}
