

package dev.zacsweers.redacted.compiler;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link dev.zacsweers.redacted.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("redacted-compiler-plugin/testData/diagnostic")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostic() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("redacted-compiler-plugin/testData/diagnostic"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("AnnotatedValueProp.kt")
  public void testAnnotatedValueProp() {
    runTest("redacted-compiler-plugin/testData/diagnostic/AnnotatedValueProp.kt");
  }

  @Test
  @TestMetadata("CustomToStringRedactedClass.kt")
  public void testCustomToStringRedactedClass() {
    runTest("redacted-compiler-plugin/testData/diagnostic/CustomToStringRedactedClass.kt");
  }

  @Test
  @TestMetadata("CustomToStringRedactedProperty.kt")
  public void testCustomToStringRedactedProperty() {
    runTest("redacted-compiler-plugin/testData/diagnostic/CustomToStringRedactedProperty.kt");
  }

  @Test
  @TestMetadata("DataObject.kt")
  public void testDataObject() {
    runTest("redacted-compiler-plugin/testData/diagnostic/DataObject.kt");
  }

  @Test
  @TestMetadata("DoubleAnnotation.kt")
  public void testDoubleAnnotation() {
    runTest("redacted-compiler-plugin/testData/diagnostic/DoubleAnnotation.kt");
  }

  @Test
  @TestMetadata("EnumClass.kt")
  public void testEnumClass() {
    runTest("redacted-compiler-plugin/testData/diagnostic/EnumClass.kt");
  }

  @Test
  @TestMetadata("NonDataClass.kt")
  public void testNonDataClass() {
    runTest("redacted-compiler-plugin/testData/diagnostic/NonDataClass.kt");
  }
}
